apiVersion: v1
kind: Service
metadata:
  name: farm-project-api-svc
spec:
  selector:
    app: farm-project-api
  ports:
    - protocol: "TCP"
      port: 8080
      nodePort: 30010
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: farm-project-front-svc
spec:
  selector:
    app: farm-project-front
  ports:
    - protocol: "TCP"
      port: 80
      nodePort: 30080
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: farm-project-api
  labels:
    app: farm-project-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: farm-project-api
  template:
    metadata:
      labels:
        app: farm-project-api
    spec:
      containers:
        - name: farm-project-api
          image: asungomez/farm-project:api
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: database-access

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: farm-project-front
  labels:
    app: farm-project-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: farm-project-front
  template:
    metadata:
      labels:
        app: farm-project-front
    spec:
      containers:
        - name: farm-project-front
          image: asungomez/farm-project:front
          ports:
            - containerPort: 80
          imagePullPolicy: Always