# kubernetes-fastapi LoadBalancer Service
# Enables the pods in a deployment to be accessible from outside the cluster
apiVersion: v1
kind: Service
metadata:
  name: farm-project-api-svc
spec:
  selector:
    app: farm-project-api
  ports:
    - protocol: "TCP"
      port: 8080
      nodePort: 30010
  type: NodePort

---
# farm-project-api Deployment
# Defines the deployment of the app running in a pod on any worker node
apiVersion: apps/v1
kind: Deployment
metadata:
  name: farm-project-api
  labels:
    app: farm-project-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: farm-project-api
  template:
    metadata:
      labels:
        app: farm-project-api
    spec:
      containers:
        - name: farm-project-api
          image: asungomez/farm-project:api
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: database-access